<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="PSAPAC518" name="test.kingsbury_Prod" tests="17" failures="3" timestamp="24 Feb 2022 05:16:50 GMT" time="121.853" errors="0">
  <testcase name="login_backend" time="17.934" classname="test.kingsbury_Prod"/>
  <testcase name="topMenuItems" time="3.062" classname="test.kingsbury_Prod"/>
  <testcase name="goToAJob" time="5.405" classname="test.kingsbury_Prod"/>
  <testcase name="reviewModeJobGrid" time="13.042" classname="test.kingsbury_Prod">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Application tab not loaded properly expected [Applications] but found [Applications:]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Application tab not loaded properly expected [Applications] but found [Applications:]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at test.kingsbury_Prod.reviewModeJobGrid(kingsbury_Prod.java:220)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- reviewModeJobGrid -->
  <testcase name="CreateaJob" time="16.721" classname="test.kingsbury_Prod"/>
  <testcase name="externalSearch" time="7.696" classname="test.kingsbury_Prod"/>
  <testcase name="Interviews" time="5.469" classname="test.kingsbury_Prod"/>
  <testcase name="JobRequest" time="3.872" classname="test.kingsbury_Prod">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Application tab not loaded properly expected [Applications] but found [Applications:]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Application tab not loaded properly expected [Applications] but found [Applications:]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at test.kingsbury_Prod.JobRequest(kingsbury_Prod.java:472)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- JobRequest -->
  <testcase name="TalentFolderProcessesr" time="4.331" classname="test.kingsbury_Prod"/>
  <testcase name="Locations" time="2.498" classname="test.kingsbury_Prod"/>
  <testcase name="HiringManagerFeedback" time="4.726" classname="test.kingsbury_Prod">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Application tab not loaded properly expected [Applications] but found [Applications:]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Application tab not loaded properly expected [Applications] but found [Applications:]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at test.kingsbury_Prod.HiringManagerFeedback(kingsbury_Prod.java:542)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- HiringManagerFeedback -->
  <testcase name="Holiday" time="2.318" classname="test.kingsbury_Prod"/>
  <testcase name="EmailQueueAdmin" time="6.237" classname="test.kingsbury_Prod"/>
  <testcase name="OrbeonForm" time="7.182" classname="test.kingsbury_Prod"/>
  <testcase name="DocumentTemplates" time="5.355" classname="test.kingsbury_Prod"/>
  <testcase name="ProcessDesigner" time="5.739" classname="test.kingsbury_Prod"/>
  <testcase name="delete_candidate" time="10.266" classname="test.kingsbury_Prod"/>
</testsuite> <!-- test.kingsbury_Prod -->
